# Generated by Django 5.0.4 on 2024-05-09 07:13

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable_components',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='component_section', to='TMS.section')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subjects',
            new_name='subjects_1',
        ),
        migrations.AddField(
            model_name='subject',
            name='subjects_3',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), default=['None', 'None'], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable_components',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_subjects', to='TMS.subject'),
        ),
        migrations.AddField(
            model_name='timetable_components',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_teacher', to='TMS.teacher'),
        ),
    ]
