# Generated by Django 5.0.4 on 2024-05-09 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0003_alter_timetable_components_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable_components',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_section', to='TMS.section'),
        ),
    ]
