# Generated by Django 5.0.4 on 2024-05-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0004_alter_timetable_components_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subjects_3',
        ),
    ]
