# Generated by Django 5.0.4 on 2024-05-12 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0005_remove_subject_subjects_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subjects_1',
        ),
        migrations.AddField(
            model_name='subject',
            name='subjects',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subject', to='TMS.subject'),
            preserve_default=False,
        ),
    ]
