# Generated by Django 5.0.4 on 2024-05-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0006_remove_subject_subjects_1_subject_subjects_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subjects',
            new_name='subject_name',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(default='A', max_length=5),
            preserve_default=False,
        ),
    ]
