# Generated by Django 5.0.4 on 2024-05-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0007_rename_subjects_subject_subject_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(related_name='teacher_subject', to='TMS.subject'),
        ),
    ]
