# Generated by Django 5.0.4 on 2024-05-12 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0008_remove_teacher_subjects_teacher_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subject', to='TMS.teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetable_components',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_subject', to='TMS.subject'),
        ),
    ]
