# Generated by Django 5.0.4 on 2024-05-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0009_remove_teacher_subjects_subject_subject_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='credit_hrs',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
